global using AutoMapper;
global using CoinSelector.Data;
global using CoinSelector.Services.Interfaces;
global using CoinSelector.Services.Mappers;
global using CoinSelector.Services.Services;
global using CoinSelector.UnitTests.Fixtures;
global using MockQueryable.Moq;
global using Moq;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Xunit;
global using Entity = CoinSelector.Data.Entities;
global using Model = CoinSelector.Models;
